#!/usr/bin/env bash
# Calibrates the inter-node distance for Module/UW/PHYSICAL that produces
# each target Packet Error Rate (PER) level (10%, 20%, ..., 100%), WITHOUT
# touching any C++. Module/UW/PHYSICAL has no direct "set PER=X" knob -- PER
# there is an emergent property of its SNR/BER model (BER=0.5*erfc(sqrt(SNR)),
# PER=1-(1-BER)^nbits) as a function of inter-node distance (fixed txpower/
# freq/bw/bitrate). This script empirically searches (exponential expansion +
# bisection) for the distance whose average observed PER lands on each
# target, reusing samples/test_uwpqc_seed_per_matrix.tcl with a single
# representative KEM/signature combo -- PER is a physical-layer property,
# independent of which auth algorithm runs on top of it.
#
# Requires the DESERT environment to already be sourced (source
# <dest_folder>/environment).
#
# Usage: ./calibrate_per_distance.sh [trials_per_candidate] [tolerance] [max_iters]
# Writes:
#   uwpqc_per_distance_calibration.csv - per,distance,avg_per,trials,iterations
#   uwpqc_per_distance_calibration.tcl - `array set per_distance {...}` for a
#                                          physical-layer sweep driver to source
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDON_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if ! command -v ns >/dev/null 2>&1; then
    echo "error: 'ns' not found in PATH -- source <dest_folder>/environment first" >&2
    exit 1
fi

# Prepend the addon's own .libs/ for dev builds that were compiled but not yet installed.
export LD_LIBRARY_PATH="$ADDON_DIR/.libs${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

cd "$ADDON_DIR" || exit 1

TRIALS="${1:-10}"
TOLERANCE="${2:-0.005}"
MAX_ITERS="${3:-20}"
DIST_FLOOR=1300.0
HI_CAP=4000.0

CAL_KEM="NTRU-HPS-2048-509"
CAL_SIG="Falcon-512"

PER_LEVELS=(0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0)

CAL_CSV="./uwpqc_per_distance_calibration.csv"
CAL_TCL="./uwpqc_per_distance_calibration.tcl"
echo "per,distance,avg_per,trials,iterations" > "$CAL_CSV"
{
    echo "# Auto-generated by samples/calibrate_per_distance.sh."
    echo "# Distance (m) calibrated per target PER for Module/UW/PHYSICAL."
    echo "array set per_distance {}"
} > "$CAL_TCL"

# measure_per DISTANCE -> prints aggregate empirical PER (sum lost / sum
# sent, across both nodes) over $TRIALS runs at that distance, each with a
# fresh random seed.
measure_per() {
    local distance="$1"
    local total_lost=0
    local total_sent=0
    for ((t = 0; t < TRIALS; t++)); do
        local seed=$RANDOM
        local out lost0 lost1 sent0 sent1
        out=$(ns samples/test_uwpqc_seed_per_matrix.tcl "$CAL_KEM" "$CAL_SIG" "$seed" "$distance" 2>/dev/null | grep '^RESULT|')
        lost0=$(printf '%s\n' "$out" | grep -oE 'phy_pkts_lost0=[0-9]+' | cut -d= -f2)
        lost1=$(printf '%s\n' "$out" | grep -oE 'phy_pkts_lost1=[0-9]+' | cut -d= -f2)
        sent0=$(printf '%s\n' "$out" | grep -oE 'phy_pkts_sent0=[0-9]+' | cut -d= -f2)
        sent1=$(printf '%s\n' "$out" | grep -oE 'phy_pkts_sent1=[0-9]+' | cut -d= -f2)
        total_lost=$((total_lost + ${lost0:-0} + ${lost1:-0}))
        total_sent=$((total_sent + ${sent0:-0} + ${sent1:-0}))
    done
    awk -v l="$total_lost" -v s="$total_sent" 'BEGIN { if (s > 0) printf "%.4f", l / s; else print "0.0000" }'
}

echo "Calibrating ${#PER_LEVELS[@]} PER levels ($TRIALS trials/candidate, tolerance=$TOLERANCE)..."
lo="$DIST_FLOOR"
cal_started=$(date +%s)

for target in "${PER_LEVELS[@]}"; do
    echo "== target PER=$target =="

    # Exponential expansion: grow hi until its measured PER >= target (PER is
    # monotonically non-decreasing in distance), so bisection has a valid bracket.
    hi=$(awk -v lo="$lo" 'BEGIN { v = lo * 1.15; if (v - lo < 20) v = lo + 20; printf "%.2f", v }')
    hi_per=$(measure_per "$hi")
    expand_iters=0
    while awk -v p="$hi_per" -v t="$target" 'BEGIN{exit !(p < t)}' && \
          awk -v h="$hi" -v c="$HI_CAP" 'BEGIN{exit !(h < c)}'; do
        lo="$hi"
        hi=$(awk -v h="$hi" 'BEGIN { printf "%.2f", h * 1.15 }')
        hi_per=$(measure_per "$hi")
        expand_iters=$((expand_iters + 1))
        if (( expand_iters > 20 )); then break; fi
    done

    mid="$hi"
    mid_per="$hi_per"
    iters=0
    for ((iters = 1; iters <= MAX_ITERS; iters++)); do
        mid=$(awk -v a="$lo" -v b="$hi" 'BEGIN { printf "%.2f", (a + b) / 2 }')
        mid_per=$(measure_per "$mid")
        echo "  iter $iters: distance=$mid -> avg_per=$mid_per (target=$target, bracket=[$lo,$hi])"

        within_tol=$(awk -v p="$mid_per" -v t="$target" -v tol="$TOLERANCE" \
            'BEGIN { d = p - t; if (d < 0) d = -d; print (d <= tol) ? "1" : "0" }')
        if [[ "$within_tol" == "1" ]]; then
            break
        fi

        lower=$(awk -v p="$mid_per" -v t="$target" 'BEGIN{print (p < t) ? "1" : "0"}')
        if [[ "$lower" == "1" ]]; then
            lo="$mid"
        else
            hi="$mid"
        fi
    done

    echo "$target,$mid,$mid_per,$TRIALS,$iters" >> "$CAL_CSV"
    echo "set per_distance($target) $mid" >> "$CAL_TCL"
    echo "-> calibrated distance for PER=$target: $mid m (measured avg_per=$mid_per)"
    echo

    # Next target's search starts from this target's distance (PER is
    # monotonic in distance), narrowing the search space for later levels.
    lo="$mid"
done

cal_elapsed=$(( $(date +%s) - cal_started ))
echo "Calibration complete in ${cal_elapsed}s."
echo "Distance table: $CAL_CSV"
echo "Tcl source file for a physical-layer sweep driver: $CAL_TCL"
echo
column -t -s',' "$CAL_CSV"
